### PR TITLE
Added another parameter for performance test.

### PR DESCRIPTION
**Pull request by jirihnidek**

### CODE REVIEW

**Comment by vritant** [comment]
@jirihnidek this defines the param, but is missing the use of the param. could you also publish the respective PR in the caracalla repo to use the variable please?

**Comment by jirihnidek** [comment]
@vritant Sorry, didn't mention it. It should be fixed now.

Here is caracalla PR: https://github.com/candlepin/caracalla/pull/29

Default value of `database_snapshot` variable: https://github.com/candlepin/caracalla/blob/jhnidek/scripts_refactoring/ansible/roles/hypervisor/defaults/main.yml

Task using `database_snapshot` variable: https://github.com/candlepin/caracalla/blob/jhnidek/scripts_refactoring/ansible/roles/hypervisor/tasks/main.yml

**Comment by vritant** [comment]
@jirihnidek  shouldnt we need a baseline and an expected dict per branch supported by the test setup too?

**Comment by jirihnidek** [comment]
@vritant I don't think it is necessary. As you can see here:

[Vritant removed jenkins link]

this performance test for candlepin-2.0-HOTFIX branch is passing with parameters created for master branch.

If it will be necessary to have separate baseline and en expected dict per branch, then special `choiceParam()` needn't to be add and we can reuse `choiceParam()` for `database_snapshot`. May be we can only do some suitable renaming of `database_snapshot` to `target_branch`?

**Comment by jirihnidek** [comment]
[Ensure performance test setup can run against 2.0-HOTFIX](https://trello.com/c/CDcd2bqC/491-ensure-performance-test-setup-can-run-against-20-hotfix)

**Comment by vritant** [comment]
@jirihnidek while the baseline may pass now, I dont think it will suffice for long. I dont mind if we re-use the choice param, but I think we should do something about it. i'd request we either do something in this PR, or at least in a follow up PR.

**Comment by jirihnidek** [comment]
I vote for doing it in different PR.

**Pull request merged**
